add wpf core support for certain plugins
MvvmCross/MvvmCross pull request #3867
Opened 2020-08-14 06:29 UTC by mashbrno

Network, ResourceLocalization and Visibility plugins can support WPF on .NET Core platform. The only change was to include WPF source codes in .netcore3.1 build. 

**Caveat**: I'm not sure, how to correctly reference WPF core libraries like `PresentationFramework` or `WindowsBase`

2020-08-14 06:55 UTC, Cheesebaron commented
Yeah, I don't think that is the right way to reference the WPF netcore libraries.

I've seen CefSharp do something like in their netcore WPF projects. Not sure if it is possible to put conditions on these to only load when target is netcore:

```
<Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk.WindowsDesktop" />
<Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk.WindowsDesktop" />
```

2020-08-14 13:46 UTC, martijn00 commented
See https://github.com/Baseflow/XamarinMediaManager/blob/develop/MediaManager.Forms/MediaManager.Forms.csproj#L13

2020-08-14 15:24 UTC, mashbrno commented
Thank you. That easy line works on my computer. I am eager to see wheter it will work on Azure Pipeline, but there is an issue with Sonar credentials.

2020-08-20 13:26 UTC, martijn00 requested changes

2020-08-20 13:26 UTC, martijn00 commented on MvvmCross.Plugins/ResourceLoader/MvvmCross.Plugin.ResourceLoader.csproj
> +    <UseWPF>true</UseWPF>
`<UseWPF Condition=" '$(OS)' == 'Windows_NT' ">true</UseWPF>`

2024-03-19 18:04 UTC, closed without merging