Bring back Playground.Mac and migrate it to net6
MvvmCross/MvvmCross pull request #4574
Opened 2023-02-14 13:17 UTC by snechaev

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
This PR brings back the Playground.Mac project removed during net6 migration in a f76f09fa8b7b379d43195bfa56818a7500ff7948 commit. And then migrates the Playground.Mac project to the net6.

### :arrow_heading_down: What is the current behavior?

### :new: What is the new behavior (if this is a feature change)?

### :boom: Does this PR introduce a breaking change?
No

### :bug: Recommendations for testing

### :memo: Links to relevant issues/docs

### :thinking: Checklist before submitting

- [x] All projects build
- [x] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [ ] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contributing/mvvmcross-docs-style-guide))
- [x] Rebased onto current develop

2023-02-14 13:39 UTC, snechaev commented
I'm looking into the cake build problems (VS build looks good at the same time).

2023-04-16 13:36 UTC, snechaev commented
Note to reviewers: It is easier to review this PR commit-by-commit. Moreover, the really important changes are only contained in the single small commit - 3f301d703c4ddb2eac274629140f881dd128b3b8

2023-05-30 07:04 UTC, Cheesebaron requested changes

2023-05-30 07:04 UTC, Cheesebaron commented on Projects/Playground/Playground.Mac/ChildView.cs
> +        public ChildView(IntPtr handle) : base(handle)
```suggestion
        public ChildView(NativeHandle handle) : base(handle)
```

2023-05-30 07:04 UTC, Cheesebaron commented on Projects/Playground/Playground.Mac/ModalView.cs
> +        public ModalView(IntPtr handle) : base(handle)
```suggestion
        public ModalView(NativeHandle handle) : base(handle)
```

2023-05-30 07:04 UTC, Cheesebaron commented on Projects/Playground/Playground.Mac/RootView.cs
> +        public RootView(IntPtr handle) : base(handle)
```suggestion
        public RootView(NativeHandle handle) : base(handle)
```

2023-05-30 07:04 UTC, Cheesebaron commented on Projects/Playground/Playground.Mac/SheetView.cs
> +        public SheetView(IntPtr handle) : base(handle)
```suggestion
        public SheetView(NativeHandle handle) : base(handle)
```

2023-05-30 07:04 UTC, Cheesebaron commented on Projects/Playground/Playground.Mac/Tab1View.cs
> +        public Tab1View(IntPtr handle) : base(handle)
```suggestion
        public Tab1View(NativeHandle handle) : base(handle)
```

2023-05-30 07:04 UTC, Cheesebaron commented on Projects/Playground/Playground.Mac/TabsRootView.cs
> +        public TabsRootView(IntPtr handle) : base(handle)
```suggestion
        public TabsRootView(NativeHandle handle) : base(handle)
```

2023-05-30 07:04 UTC, Cheesebaron commented on Projects/Playground/Playground.Mac/ToolbarWindow.cs
> +        public ToolbarWindow(IntPtr handle) : base(handle)
```suggestion
        public ToolbarWindow(NativeHandle handle) : base(handle)
```

2023-05-30 07:04 UTC, Cheesebaron commented on Projects/Playground/Playground.Mac/WindowView.cs
> +        public WindowView(IntPtr handle) : base(handle)
```suggestion
        public WindowView(NativeHandle handle) : base(handle)
```

2023-05-30 07:04 UTC, Cheesebaron commented on Projects/Playground/Playground.Mac/ToolbarWindow.cs
> +        }
```suggestion
```

2023-05-30 07:04 UTC, Cheesebaron commented
Please add the project to the -macos.slnf solution filter.

2023-05-30 07:05 UTC, Cheesebaron commented on Projects/Playground/Playground.Mac/Playground.Mac.sln
With the -macos.slnf solution filter, I don't find a separate solution worth having. Please remove.

2023-05-31 13:30 UTC, Cheesebaron commented
Looks good to me. Thanks!

2023-05-31 13:30 UTC, merged