Update TipCalc Android and Core tutorial
MvvmCross/MvvmCross pull request #4616
Opened 2023-06-08 12:04 UTC by Leo506

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
It is docs update

### :arrow_heading_down: What is the current behavior?
TipCalc tutorial has not information about breaking changes with Setup class

### :new: What is the new behavior (if this is a feature change)?
Actual tutorial for begginers

### :boom: Does this PR introduce a breaking change?
No

### :bug: Recommendations for testing

### :memo: Links to relevant issues/docs
https://github.com/MvvmCross/MvvmCross/issues/4469

### :thinking: Checklist before submitting

- [ ] All projects build
- [ ] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [ ] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contributing/mvvmcross-docs-style-guide))
- [ ] Rebased onto current develop

2023-06-08 12:08 UTC, Leo506 commented
> 

@dotnet-policy-service agree

2023-06-08 14:43 UTC, Cheesebaron requested changes

2023-06-08 15:10 UTC, Leo506 commented on docs/_documentation/tutorials/tipcalc/a-xamarinandroid-ui-project.md
> +- We will add a new .xml file - called `TipView.axml` into the `/Resources/Layout` folder.
Yes. I didn't notice this one

2023-06-09 07:18 UTC, Cheesebaron approved these changes

2023-06-09 07:19 UTC, Cheesebaron commented
Thanks!

2023-06-09 07:19 UTC, merged